sudo: required
services:
  - docker

before_install:
  - docker build -t agungtrue/docker-simple-react -f dockerfile.dev .

script: 
  - docker run agungtrue/docker-simple-react npm run test -- --coverage

# script:
#     - docker run -e CI=true agungtrue/docker-simple-react npm run test -- --coverage

# language: generic
# language: node_js

# deploy: 
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-simple-react"
#   env: "Dockersimplereact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-974033066148"
#   bucket_path: "docker-simple-react"
#   on:
#     branch: master